### ISSUE TITLE
Don't seem to be getting result 

### ISSUE THREAD

**Issue by adamgins** [acemtp/meteor-meta-extractor#1]
Hi, I installed the package and I am trying to retrieve a Facebook public post meta data... I don't get an error and in the result I get back and empty object:

![image](https://cloud.githubusercontent.com/assets/7233741/10806025/7f5dfcfe-7e26-11e5-8618-00d338ba0c31.png)

I tried this on the  client and server.

If I use the demo http://efounders.co/, it works fine.

Any ideas, pls?

**Comment by Ouro17** [comment]
Yes, I try too on my webpage and it doesnt work.

**Comment by acemtp** [comment]
Can you give me the page that doesn't work so I can test

**Comment by acemtp** [comment]
I added an example in the source and deployed it http://meta-extractor.meteor.com

It's possible that you don't get result because the package found nothing.

Give me the url that doesn't work and I'll check

**Comment by Ouro17** [comment]
For example https://www.libercar.com, that is my page.

I tried this package (https://atmospherejs.com/agarcia038/extract-metadata) and it works well. Maybe you can take a look at their code.

**Comment by acemtp** [comment]
Ok, I just published a fix. Tell me if you see other pages that don't work

**Comment by areejayy** [comment]
@Ouro17 hi, how did you use that agarcia038 package?

**Comment by Ouro17** [comment]
You first need to install the package using meteor add agarcia038:extract-metadata on your meteor project then on your client(on click event or something like that) just use :
Meteor.call('fetchMetadata', 'putHereYourUrl', function (error, result) {
    if(error)
{
  console.error(error);
}else
{
  console.log(result);
    //{name:'Page name',description:'Here's the metadata description',image:'img url'}
}
});

Remember to change 'putHereYourUrl' for your url. 
It's easy ;)
