### ISSUE TITLE
extracting from html string fails

### ISSUE THREAD

**Issue by vivekdtiwari** [acemtp/meteor-meta-extractor#3]
The method works smoothly when calling a url. The page mentioned it was also possible to extract from html string. So I used http package and then "result.content" contained the html string. Then next tried extractData(result.content) , however this gives undefined. Is it not possible to extract metadata from html strings?

**Comment by vivekdtiwari** [comment]
Sincerely sorry for the hasty action, on client I must pass a callback. It works awesome now.

**Comment by acemtp** [comment]
no problem :)
